apiVersion: v1
kind: Service
metadata:
  name: ianna-app-service
  namespace: ianna-app
spec:
  selector:
    app: ianna-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer